### PR TITLE
Feature Table prefix option

### PR DESCRIPTION
**Pull request by piotr-cz**
As requested in #6

### CODE REVIEW

**Comment by piotr-cz** [comment]
@raffaelj
I'll keep this PR opened till tomorrow and then merge into main branch.

If you'll find any issues while testing, please describe them here

**Comment by raffaelj** [comment]
@piotr-cz I have to do some other work in the next hours, but I think, I'll have some time for more tests later this day or tomorrow. I'll keep you updated.

**Comment by raffaelj** [comment]
I didn't have time for intensive testing, yet, but I also didn't encounter any errors while fiddling (with you latest commit pulled).

I would revert the default prefix to an empty string. This way it stays backwards compatible without config changes and if I use a separate database, I don't need the prefix.

**Comment by piotr-cz** [comment]
Default table prefix is an empty string, in README it's just an example.
But maybe it's not clear enough, I'll rephrase

**Comment by piotr-cz** [comment]
Available in [v1.0.0-rc.3](https://github.com/piotr-cz/cockpit-sql-driver/releases/tag/v1.0.0-rc.3)

**Comment by raffaelj** [comment]
> Default table prefix is an empty string, in README it's just an example.

I just remembered reading it yesterday while scrolling through the branch diff. It would have been clear enough, if I had a second look.

Thanks for the update.

**Pull request merged**
